//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

var first = 0;
var second = 1;
var sum = 0;
var i = 0;

while ( i < 100) { 
    i += second;
    i = first + second;
    if(i % 2 == 0) {sum += i };
    first = second;
    second = i;
}
console.log(sum)